### PR TITLE
Image should be better now

### PR DESCRIPTION
**Pull request by avaidyam**

### CODE REVIEW

**Comment by mattmolo** [comment]
I think we want to rename the image to png, the index is linking *.png for that image.

**Comment by avaidyam** [comment]
but im lazy

ok ill do it

**Comment by avaidyam** [comment]
Hold off on this for now actually -- I'll fix it.

**Comment by avaidyam** [comment]
Ok fine then Matt. :(

**Comment by mattmolo** [comment]
lolwhoops

**Comment by avaidyam** [comment]
heh. ;_;

**Pull request merged**
