### PR TITLE
Cleaner mailman API.

### PR DESCRIPTION
**Pull request by avaidyam**

### CODE REVIEW

**Review by stwrt — APPROVED** [review]

**Comment by avaidyam** [comment]
@brstew I have a quick fix thanks to @mattmolo to prevent something like a "shellshock" so I'll merge that ASAP.

**Comment by mattmolo** [comment]
@brstew you should get a slap too for not noticing the obvious security issue

**Comment by mattmolo** [comment]
The two repos for this seems.. kinda EH. Maybe make a submodule and have the `signup_post.php` script include `DirectoryServices/Lists.php`

**Comment by avaidyam** [comment]
@mattmolo I would do that, but am too lazy (I have done everything on the github web interface thus far) and will do that later.

**Comment by mattmolo** [comment]
I think you like to make things more difficult for yourself

**Comment by avaidyam** [comment]
@mattmolo i am dolfin

**Pull request merged**
