### PR TITLE
added ROV team pictures and names

### PR DESCRIPTION
**Pull request by rakoskr6**
After merged to the website I'll ask all ROV team leads to verify all names one last time.

### CODE REVIEW

**Comment by rakoskr6** [comment]
@michaelhayashi If you could help me verify all these people pictured paid dues as well that would be awesome

**Comment by mattmolo** [comment]
@rakoskr6 First name on electrical is definitely not Vincent Zhang

**Comment by rakoskr6** [comment]
I just copied down what Luke put! I figured it's best to just put it online and share it with team leads. They can then tell me what to correct. It's not like someone will see it/care if it's temporarily online anyway!

**Comment by michaelhayashi** [comment]
I think you mean Wen Shen "Vincent" Mow, @rakoskr6. Is this going to be our roster page?

**Comment by mattmolo** [comment]
Alright well I merged it

**Comment by mattmolo** [comment]
I fixed some names too

**Pull request merged**
